#include "fs.h"

#include <assert.h>
#include <glob.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include <time.h>

#include "log.h"

static int fswalkerr(const char* epath, const int errno) {
  log_error("error accessing `%s`: %d", epath, errno);
  return 0; /* continue glob scan */
}

int fswalk(const char* dir, fswalkfn_t filefn, fswalkfn_t dirfn, void* udata) {
  char pattern[256]; /* glob pattern format buffer */
  glob_t gres = {0}; /* glob search results */
  int ret;           /* glob return value */

  // ensure pattern has capacity for dir + wildcard suffix
  assert(strlen(dir) < sizeof(pattern));
  snprintf(pattern, sizeof(pattern), "%s/*", dir);

  if ((ret = glob(pattern, GLOB_MARK | GLOB_TILDE, fswalkerr, &gres))) {
    globfree(&gres);
    if (ret == GLOB_NOMATCH) return 0;
    return -1;
  }

#if defined(__FreeBSD__) || defined(__APPLE__)
  const int mc = gres.gl_matchc;
#else
  const int mc = gres.gl_pathc;
#endif

  // invoke process function for each result
  int err = 0;
  for (int i = 0; i < mc; i++) {
    char* fp = gres.gl_pathv[i];
    const size_t len = strlen(fp);
    if (fp[len - 1] == '/') {// if directory, invoke directory function
      fp[len - 1] = '\0';    // remove the trailing slash generated by GLOB_MARK
      if ((err = dirfn(fp, udata))) goto doret;
    } else if ((err = filefn(gres.gl_pathv[i], udata))) {
      goto doret;
    }
  }

doret:
  globfree(&gres);
  return err;
}

bool fsstateql(const struct fsstat_s* a, const struct fsstat_s* b) {
  return a->lmod == b->lmod && a->fsze == b->fsze;
}

int fsstat(const char* fp, struct fsstat_s* s) {
  struct stat st = {0};
  if (stat(fp, &st)) return -1;
#if defined(__FreeBSD__) || defined(__APPLE__)
  const struct timespec ts = st.st_mtimespec; /* last modified */
#else
  const struct timespec ts = st.st_mtim; /* last modified */
#endif
  s->lmod = ts.tv_sec * 1000 + ts.tv_nsec / 1000000; /* convert to millis */
  s->fsze = st.st_size;                              /* copy file size */
  return 0;
}
