name: CMake
on:
  push:
  pull_request:
    branches: [ "main" ]
env:
  BUILD_TYPE: RelWithDebInfo
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [ "clang", "gcc", "musl-gcc" ]
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_C_COMPILER=${{matrix.compiler}}
      - name: Build
        run: cmake --build ${{github.workspace}}/build
      - uses: actions/upload-artifact@v4
        with:
          name: fsautoproc-ubuntu-x86_64-${{matrix.compiler}}
          path: ${{github.workspace}}/build/fsautoproc
  macOS:
    runs-on: macos-latest
    steps:
      - name: Install dependencies
        run: |
          brew update
          brew install cjson include-what-you-use
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_C_COMPILER="clang"
      - name: Build
        run: cmake --build ${{github.workspace}}/build
      - uses: actions/upload-artifact@v4
        with:
          name: fsautoproc-macos-x86_64
          path: ${{github.workspace}}/build/fsautoproc