name: Valgrind
on:
  push:
  pull_request:
    branches: [ "main" ]
env:
  BUILD_TYPE: RelWithDebInfo
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcjson-dev iwyu valgrind
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_C_COMPILER="gcc"
      - name: Build
        run: cmake --build ${{github.workspace}}/build
      - name: Run Valgrind
        run: |
          valgrind --leak-check=full --error-exitcode=1 ./build/fsautoproc -h
          mkdir empty && valgrind --leak-check=full --error-exitcode=1 ./build/fsautoproc -c example.fsautoproc.json -s empty
          valgrind --leak-check=full --error-exitcode=1 ./build/fsautoproc
